"""Leaderboard: aggregate `results/*.json` written by evaluate.py into LEADERBOARD.md.

    python -m agentic_gp.leaderboard                 # writes LEADERBOARD.md
    python -m agentic_gp.leaderboard --results-dir results --out LEADERBOARD.md
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path


def load_results(results_dir: str | Path = "results") -> list[dict]:
    out = []
    for p in sorted(Path(results_dir).glob("*.json")):
        try:
            data = json.loads(p.read_text(encoding="utf-8"))
        except json.JSONDecodeError:
            continue
        data["_file"] = p.name
        out.append(data)
    return out


def sort_key(r: dict):
    best = r.get("best_lap")
    if best is None:
        # DNFs after all finishers, ordered by progress then fewest crashes
        return (1, -r.get("max_waypoints_passed", 0), r.get("total_crashes", 0))
    return (0, best, r.get("total_crashes", 0))


def render_markdown(results: list[dict], baseline_name: str = "hermes") -> str:
    results = sorted(results, key=sort_key)
    baseline = next((r for r in results if r.get("name") == baseline_name), None)
    lines = [
        "# Agentic Grand Prix - Leaderboard",
        "",
        "Best lap time = simulated time + 5 s per crash. Lower is better. DNF = did not finish a lap.",
        "",
        "| # | Agent | Best lap (s) | vs Hermes | Attempts (finished) | Crashes | Tool calls | Model | Submitted |",
        "|---|-------|-------------:|----------:|--------------------:|--------:|-----------:|-------|-----------|",
    ]
    for i, r in enumerate(results, 1):
        best = r.get("best_lap")
        best_s = f"{best:.2f}" if best is not None else "DNF"
        if baseline and baseline.get("best_lap") is not None and best is not None:
            delta = best - baseline["best_lap"]
            vs = f"{delta:+.2f}"
        elif baseline and baseline.get("best_lap") is None and best is not None:
            vs = "beats DNF"
        else:
            vs = "-"
        n_att = len(r.get("attempts", []))
        n_fin = sum(1 for a in r.get("attempts", []) if a.get("completed"))
        name = r.get("name", r["_file"])
        if name == baseline_name:
            name = f"**{name}** (baseline)"
        lines.append(
            f"| {i} | {name} | {best_s} | {vs} | {n_att} ({n_fin}) | {r.get('total_crashes', 0)} | "
            f"{r.get('tool_calls', '-')} | {r.get('model', '-')} | {str(r.get('timestamp', ''))[:19]} |"
        )
    if not results:
        lines.append("| - | *(no results yet)* | | | | | | | |")
    lines += ["", f"_{len(results)} entries. Generated by `python -m agentic_gp.leaderboard`._"]
    return "\n".join(lines) + "\n"


def main(argv: list[str] | None = None) -> None:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--results-dir", default="results")
    ap.add_argument("--out", default="LEADERBOARD.md")
    ap.add_argument("--baseline", default="hermes")
    args = ap.parse_args(argv)
    md = render_markdown(load_results(args.results_dir), baseline_name=args.baseline)
    Path(args.out).write_text(md, encoding="utf-8")
    print(md)


if __name__ == "__main__":
    main()
